In [8]:
import pandas as pd
import numpy as np
import scipy.io
import scipy.io as sio
from scipy.io import loadmat
import chardet
import csv

In [44]:
#left1
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left1.csv', 'rb') as f:
            data = f.read()
sensor1 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor1['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left1.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor1 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor1 = new_sensor1.rename(columns=column_names)

new_sensor1.columns = ['1', 'left1', '3', '4']  # # rename column
new_sensor1.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 10 row
new_sensor1 = new_sensor1.iloc[12:]
# Reset the index
new_sensor1 = new_sensor1.reset_index(drop=True)

# new_sensor1['left1'] = new_sensor1['left1'].astype(float)
new_sensor1 = new_sensor1.astype(float)

new_sensor1.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal//WHJ_N2_L1.csv', index=False)

new_sensor1
# new_sensor1.dtypes

left1
0      -0.022750
1      -0.022750
2      -0.020073
3      -0.020073
4      -0.020073
...          ...
196351 -0.020073
196352 -0.022750
196353 -0.022750
196354 -0.020073
196355 -0.025426

[196356 rows x 1 columns]

In [45]:
#left2
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left2.csv', 'rb') as f:
            data = f.read()
sensor2 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor2['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left2.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor2 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor2 = new_sensor2.rename(columns=column_names)

new_sensor2.columns = ['1', 'left2', '3', '4']  # # rename column
new_sensor2.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 10 row
new_sensor2 = new_sensor2.iloc[12:]
# Reset the index
new_sensor2 = new_sensor2.reset_index(drop=True)

new_sensor2 = new_sensor2.astype(float)

new_sensor2.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal/WHJ_N2_L2.csv', index=False)

new_sensor2

left2
0      -0.014720
1      -0.014720
2      -0.017397
3      -0.012044
4      -0.028103
...          ...
196375 -0.012044
196376 -0.022750
196377  0.020073
196378  0.062896
196379  0.046838

[196380 rows x 1 columns]

In [46]:
#left3
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left3.csv', 'rb') as f:
            data = f.read()
sensor3 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor3['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left3.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor3 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor3 = new_sensor3.rename(columns=column_names)

new_sensor3.columns = ['1', 'left3', '3', '4']  # # rename column
new_sensor3.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 10 row
new_sensor3 = new_sensor3.iloc[12:]
# Reset the index
new_sensor3 = new_sensor3.reset_index(drop=True)

new_sensor3 = new_sensor3.astype(float)

new_sensor3.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal/WHJ_N2_L3.csv', index=False)

new_sensor3

left3
0       0.009368
1       0.009368
2       0.006691
3       0.012044
4       0.006691
...          ...
196411  0.017397
196412  0.036132
196413  0.044161
196414  0.020073
196415 -0.004014

[196416 rows x 1 columns]

In [47]:
#left4
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left4.csv', 'rb') as f:
            data = f.read()
sensor4 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor4['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_left4.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor4 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor4 = new_sensor4.rename(columns=column_names)

new_sensor4.columns = ['1', 'left4', '3', '4']  # # rename column
new_sensor4.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 10 row
new_sensor4 = new_sensor4.iloc[12:]
# Reset the index
new_sensor4 = new_sensor4.reset_index(drop=True)

new_sensor4 = new_sensor4.astype(float)

new_sensor4.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal/WHJ_N2_L4.csv', index=False)

new_sensor4

left4
0       0.020073
1       0.020073
2       0.025426
3       0.022749
4       0.022749
...          ...
196411 -0.033455
196412 -0.033455
196413 -0.020073
196414  0.033455
196415  0.073602

[196416 rows x 1 columns]

In [48]:
#right1
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right1.csv', 'rb') as f:
            data = f.read()
sensor5 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor5['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right1.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor5 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor5 = new_sensor5.rename(columns=column_names)

new_sensor5.columns = ['1', 'right1', '3', '4']  # # rename column
new_sensor5.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 12 row
new_sensor5 = new_sensor5.iloc[12:]
# Reset the index
new_sensor5 = new_sensor5.reset_index(drop=True)

new_sensor5 = new_sensor5.astype(float)

new_sensor5.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal/WHJ_N2_R1.csv', index=False)

new_sensor5

right1
0       0.052190
1       0.049514
2       0.046838
3       0.052190
4       0.049514
...          ...
196327  0.041485
196328  0.054867
196329  0.062896
196330  0.057543
196331  0.060220

[196332 rows x 1 columns]

In [49]:
#right2
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right2.csv', 'rb') as f:
            data = f.read()
sensor6 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor6['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right2.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor6 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor6 = new_sensor6.rename(columns=column_names)

new_sensor6.columns = ['1', 'right2', '3', '4']  # # rename column
new_sensor6.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 12 row
new_sensor6 = new_sensor6.iloc[12:]
# Reset the index
new_sensor6 = new_sensor6.reset_index(drop=True)

new_sensor6 = new_sensor6.astype(float)

new_sensor6.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal/WHJ_N2_R2.csv', index=False)

new_sensor6

right2
0      -0.009367
1      -0.009367
2      -0.009367
3      -0.012044
4      -0.006691
...          ...
196375 -0.009367
196376 -0.006691
196377 -0.006691
196378 -0.009367
196379 -0.009367

[196380 rows x 1 columns]

In [50]:
#right3
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right3.csv', 'rb') as f:
            data = f.read()
sensor7 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor7['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right3.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor7 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor7 = new_sensor7.rename(columns=column_names)

new_sensor7.columns = ['1', 'right3', '3', '4']  # # rename column
new_sensor7.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 12 row
new_sensor7 = new_sensor7.iloc[12:]
# Reset the index
new_sensor7 = new_sensor7.reset_index(drop=True)

new_sensor7 = new_sensor7.astype(float)

new_sensor7.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal/WHJ_N2_R3.csv', index=False)

new_sensor7

right3
0       0.017397
1       0.012044
2       0.014720
3       0.012044
4       0.012044
...          ...
196411  0.033455
196412  0.081632
196413  0.070926
196414  0.028102
196415  0.004015

[196416 rows x 1 columns]

In [51]:
#right4
# open and use chardet to detect the encoding
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right4.csv', 'rb') as f:
            data = f.read()
sensor8 = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor8['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/row_data/WHJ_normal2_right4.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]

# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}

# Convert the data to a Pandas DataFrame and rename the columns
new_sensor8 = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor8 = new_sensor8.rename(columns=column_names)

new_sensor8.columns = ['1', 'right4', '3', '4']  # # rename column
new_sensor8.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# delete first 12 row
new_sensor8 = new_sensor8.iloc[12:]
# Reset the index
new_sensor8 = new_sensor8.reset_index(drop=True)

new_sensor8 = new_sensor8.astype(float)

new_sensor8.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/decode/normal/WHJ_N2_R4.csv', index=False)

new_sensor8

right4
0       0.001338
1      -0.001338
2       0.001338
3       0.001338
4       0.004015
...          ...
196351 -0.009367
196352 -0.001338
196353  0.009368
196354  0.017397
196355  0.014720

[196356 rows x 1 columns]

In [52]:
all_data = pd.concat([new_sensor1, new_sensor2, new_sensor3, new_sensor4, new_sensor5, new_sensor6, new_sensor7, new_sensor8], axis=1)  
# data_split.head(20)
all_data

left1     left2     left3     left4    right1    right2    right3  \
0      -0.022750 -0.014720  0.009368  0.020073  0.052190 -0.009367  0.017397   
1      -0.022750 -0.014720  0.009368  0.020073  0.049514 -0.009367  0.012044   
2      -0.020073 -0.017397  0.006691  0.025426  0.046838 -0.009367  0.014720   
3      -0.020073 -0.012044  0.012044  0.022749  0.052190 -0.012044  0.012044   
4      -0.020073 -0.028103  0.006691  0.022749  0.049514 -0.006691  0.012044   
...          ...       ...       ...       ...       ...       ...       ...   
196411       NaN       NaN  0.017397 -0.033455       NaN       NaN  0.033455   
196412       NaN       NaN  0.036132 -0.033455       NaN       NaN  0.081632   
196413       NaN       NaN  0.044161 -0.020073       NaN       NaN  0.070926   
196414       NaN       NaN  0.020073  0.033455       NaN       NaN  0.028102   
196415       NaN       NaN -0.004014  0.073602       NaN       NaN  0.004015   

          right4  
0       0.001338  
1      -0.001338  
2       0.001338  
3       0.001338  
4       0.004015  
...          ...  
196411       NaN  
196412       NaN  
196413       NaN  
196414       NaN  
196415       NaN  

[196416 rows x 8 columns]

In [53]:
#Remove redundant data at the beginning and end according to the video
#Delete last end rows 
# new_dat = WYH_normal1.drop(WYH_normal1.index[-5:], inplace=True)
new_dat = all_data.drop(all_data.index[195208:])
# new_dat
# delete first start row
new_dat = new_dat.iloc[3739:]
# Reset the index
new_dat = new_dat.reset_index(drop=True)

new_dat.to_csv('/Users/jiaxuan/Library/CloudStorage/Dropbox/WorkSpace/GaitData/WHJ_20230313/normal/all_WHJ_N2.csv', index=False)

new_dat

left1     left2     left3     left4    right1    right2    right3  \
0      -0.025426 -0.009367 -0.022750  0.062896  0.062896 -0.006691  0.009368   
1      -0.020073 -0.004014 -0.025426  0.060220  0.062896 -0.017397  0.012044   
2      -0.022750 -0.001338 -0.036132  0.073602  0.046838 -0.012044  0.014720   
3      -0.022750 -0.004014 -0.025426  0.057543  0.046838  0.001338  0.017397   
4      -0.025426  0.004015 -0.001338  0.036132  0.044161  0.001338  0.014720   
...          ...       ...       ...       ...       ...       ...       ...   
191464 -0.025426  0.004015 -0.006691  0.049514  0.057543 -0.017397  0.012044   
191465 -0.022750 -0.004014  0.001338  0.103043  0.033455 -0.022750  0.012044   
191466 -0.025426 -0.006691  0.006691  0.140513  0.017397 -0.028103  0.004015   
191467 -0.025426 -0.017397  0.004015  0.086984  0.012044 -0.028103 -0.006691   
191468 -0.022750 -0.006691  0.004015 -0.012044  0.017397 -0.022750  0.014720   

          right4  
0       0.028102  
1       0.009368  
2      -0.012044  
3       0.004015  
4       0.012044  
...          ...  
191464 -0.012044  
191465 -0.014720  
191466 -0.006691  
191467  0.004015  
191468  0.001338  

[191469 rows x 8 columns]

In [121]:
# npy
mat_data = scipy.io.loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/all_feature.mat')
data = mat_data['Feature_vec']
print(data.shape)
num_data = np.stack(data.ravel()).reshape((-1, 8, 5))
print(num_data.shape)
print(num_data[0])
np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/all_WHJ_checked', num_data)

(1, 1763)
(1763, 8, 5)
[[ 1.04411312 -1.17415945  1.32861214 -6.06607975  0.02559628]
 [ 4.95858365 -0.45608091  6.71867883 -4.50812744  0.06270344]
 [10.366269   -0.11983166 13.23142343 -3.77069041  0.09159223]
 [ 7.57238002 -0.28024137  9.32601962 -4.08474016  0.07681816]
 [ 4.65468213 -0.5028375   5.77064766 -4.57137396  0.05879871]
 [ 8.1293494  -0.19199047 10.90492816 -4.01376669  0.0888746 ]
 [ 9.80235694 -0.12831942 12.38170192 -3.82662472  0.09743091]
 [ 6.94760146 -0.23168942  8.79234097 -4.1708511   0.07538692]]


In [109]:
mat_data = scipy.io.loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/all_feature.mat')
# mat_data
cell_data = mat_data['Feature_vec'][0]
cell_data
cell_data.shape

# np_data = np.empty((len(cell_data), *cell_data[0].shape, 1), dtype=np.float64)
# for i in range(len(cell_data)):
#     np_data[i, :, :, 0] = cell_data[i]
# print(np_data.shape)
# np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_FeaVec5_data4.np', np_data)

(1763,)

In [117]:
mat_data = loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/all_feature.mat')['Feature_vec']
print(mat_data.shape)
# Convert to numpy array
np_data = np.array([mat_data[i][0] for i in range(mat_data.shape[0])])
print(np_data.shape)

np_data = np_data.reshape((1788, 8, 5))
print(np_data.shape)



(1, 1763)
(1, 8, 5)


ValueError: cannot reshape array of size 40 into shape (1788,8,5)

In [96]:
mat_data = loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/row_data/EMG_t.mat')['EMG_t']
np_data = np.stack([cell[0] for cell in mat_data], axis=0)
print(np_data.shape)
# np_data = np_data.reshape((1788, 8, 1800)).transpose((0, 1, 2))
np_data = np_data.reshape((1788, 8, 1800))
print(np_data.shape)
print(np_data[0])
np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/row_data/row_EMG', np_data)

(1788, 1800, 8)
(1788, 8, 1800)
[[-0.01365348 -0.02540146  0.01303043 ...  0.02034423 -0.15089137
  -0.04488434]
 [-0.01785461 -0.02497719  0.01547958 ...  0.00978721  0.01011673
   0.01033947]
 [-0.01785461 -0.01657493 -0.00217422 ... -0.09764115  0.01935808
   0.11166576]
 ...
 [-0.00945235 -0.12455074  0.01320793 ...  0.00680947 -0.02365204
  -0.00925949]
 [-0.00945235 -0.0699372   0.00138653 ... -0.0705837   0.16216544
   0.12378374]
 [-0.01785461 -0.01447437  0.01546825 ...  0.03157688 -0.01365459
   0.00027725]]


In [ ]:

mat_data = loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/row_data/EMG_t.mat')['EMG_t']

# Convert to numpy array
np_data = np.array([mat_data[i][0] for i in range(mat_data.shape[0])])

# Reshape to (1788, 8, 1800) shape
np_data = np_data.reshape((1788, 8, 1800))

# Save as .npy file
np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/row_data/row_EMG', np_data)


In [105]:
# filter

mat_data = loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/all_feature.mat')['Feature_vec']
print(mat_data.shape)
np_data = np.array([mat_data[i][0] for i in range(mat_data.shape[0])])
print(np_data.shape)
print(np_data[0])
np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/all_chack', np_data)

(1, 1763)
(1, 8, 5)
[[ 63.11598192   0.58291513 447.38673771  -1.96427357   0.99180633]
 [ 67.51900244   0.59862778 449.40657567  -1.89683851   0.99402863]
 [ 59.27501282   0.53522226 445.96634068  -2.02705973   0.99169653]
 [ 63.67091371   0.57772155 436.39619995  -1.95551974   0.97660155]
 [ 60.60664196   0.56961825 449.9587629   -2.00484309   0.99471629]
 [ 67.7752298    0.60055023 443.41420578  -1.8930508    0.98615683]
 [ 72.66931417   0.62962365 457.11287712  -1.82332838   1.00147648]
 [ 68.23945989   0.60646388 456.91117086  -1.88622459   1.0053331 ]]


In [ ]:
mat_data = scipy.io.loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/Feature/Feature_vec.mat')
data = mat_data['Feature_vec']

num_data = np.stack(data.ravel()).reshape((-1, 8, 5))

np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_FeaVec5_data3.np', num_data)

In [66]:

# Load data from .mat file
mat_data = loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/data_chack/row_data/row_segment_emg_all.mat')['row_segment_emg_all']
print(mat_data.shape)
 # Convert to numpy array
np_data = np.array(mat_data)
print(np_data.shape)
# # # Transpose to (1788, 8, 1800) shape
# np_data = np_data.reshape((1788, 1800, 8)).transpose((0, 2, 1))
# np_data
# # Save as .npy file
# np.save('row_segment_emg_all.npy', np_data)


(1788, 1)
(1788, 1)


In [48]:
mat_data = scipy.io.loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/Feature/Feature_vec.mat')
data = mat_data['Feature_vec']

num_data = np.stack(data.ravel()).reshape((-1, 8, 5))

np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_FeaVec5_data3.np', num_data)

In [22]:
data[0][0]

array([[ 61.21970773,   0.56482282, 459.452678  ,  -1.99477842,
          1.01185731],
       [ 66.08219052,   0.58663752, 457.38860848,  -1.9183483 ,
          1.00560696],
       [ 63.75108724,   0.57477116, 452.13527336,  -1.95426134,
          0.99754405],
       [ 66.63450059,   0.59340906, 456.64544032,  -1.91002511,
          1.00303475],
       [ 66.10472102,   0.58273269, 440.78082475,  -1.91800742,
          0.98046995],
       [ 62.82081636,   0.57039952, 452.92227251,  -1.96896109,
          1.00266208],
       [ 67.50683235,   0.60331308, 455.14054177,  -1.89701877,
          1.0048313 ],
       [ 63.54772192,   0.56869832, 453.3255057 ,  -1.95745643,
          0.99999422]])

In [23]:
num_data[0][0]

array([ 61.21970773,   0.56482282, 459.452678  ,  -1.99477842,
         1.01185731])

In [33]:
# Load CSV file
data = np.loadtxt('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_index.csv')
print(data.shape)
print(data)
# Reshape array
data = data.reshape((-1, 1))
print(data.shape)
print(data)
# Save reshaped array as CSV file
np.savetxt('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_index1.csv', data, delimiter=',')

(1763,)
[0. 0. 0. ... 2. 2. 2.]
(1763, 1)
[[0.]
 [0.]
 [0.]
 ...
 [2.]
 [2.]
 [2.]]


In [14]:
data = scipy.io.loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/Feature/Feature_vec.mat')
Feature_vec = np.array(data)
np.save("/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_FeaVec5_data.npy", Feature_vec)

In [8]:
mat_data = scipy.io.loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/Feature/Feature_vec.mat')
numeric_data = mat_data['Feature_vec']
np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_FeaVec5_data1.np', mat_data)

In [11]:


# Load data from .mat file into a Python dictionary
mat_data = scipy.io.loadmat('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/Feature/Feature_vec.mat')

# Extract cell data from dictionary
cell_data = mat_data['Feature_vec']

# Convert cell data to NumPy array
num_data = np.array(cell_data)

num_data = num_data.reshape((1, 1763, 5, 8))

# Save NumPy array as .npy file
np.save('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/WYH_FeaVec5_data2.np', num_data)


ValueError: cannot reshape array of size 1763 into shape (1,1763,5,8)

In [84]:
# new_dat.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/normal/all_WYH_normal3.csv', index=False)
# new_dat.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/toe_in/all_WYH_toein.csv', index=False)
new_dat.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/supination/WYH_supination1.csv', index=False)
# new_dat.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/pronation/name_pronation_modified.csv', index=False)
# new_dat.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/supination/name_supination_modified.csv', index=False)

In [25]:
# Create new_dat index
new_dat = pd.DataFrame({'index': [2]*555120})

# Write the dataframe to a CSV file
new_dat.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/toe_in/all_WYH_toein_index.csv', index=False)

In [27]:
# check index
new_dat = pd.read_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/toe_in/all_WYH_toein_index.csv')
new_dat

index
0           2
1           2
2           2
3           2
4           2
...       ...
555115      2
555116      2
555117      2
555118      2
555119      2

[555120 rows x 1 columns]

In [52]:
new_dat = pd.read_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/normal/all_WYH_normal1.csv')
new_dat

left1     left2     left3     left4    right1    right2    right3  \
0      -0.017397 -0.025426  0.020073  0.028102  0.041485 -0.006691  0.111072   
1      -0.017397 -0.054867  0.022749  0.033455  0.041485  0.030779  0.121777   
2      -0.022750 -0.057543  0.041485  0.041485  0.046838  0.041485  0.086984   
3      -0.017397 -0.076278  0.054867  0.044161  0.046838  0.049514  0.084308   
4      -0.022750 -0.046837  0.057543  0.046838  0.041485  0.070926  0.097690   
...          ...       ...       ...       ...       ...       ...       ...   
181875 -0.028103 -0.014720  0.012044  0.014720  0.038808 -0.009367  0.006691   
181876 -0.025426 -0.012044  0.009368  0.022749  0.041485 -0.009367  0.020073   
181877 -0.025426 -0.014720  0.014720  0.022749  0.041485 -0.004014  0.022749   
181878 -0.028103 -0.014720  0.009368  0.022749  0.036132 -0.012044  0.030779   
181879 -0.020073 -0.014720  0.009368  0.017397  0.038808 -0.014720  0.030779   

          right4  
0       0.020073  
1       0.014720  
2       0.006691  
3       0.009368  
4       0.014720  
...          ...  
181875 -0.006691  
181876 -0.009367  
181877 -0.006691  
181878 -0.004014  
181879 -0.001338  

[181880 rows x 8 columns]

In [28]:
# new_dat = pd.read_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/toe_in/all_WYH_toein.csv')
# new_dat

In [29]:
# create a DataFrame with 10 rows of data
df = pd.DataFrame({'A': range(10), 'B': range(10, 20)})
df

A   B
0  0  10
1  1  11
2  2  12
3  3  13
4  4  14
5  5  15
6  6  16
7  7  17
8  8  18
9  9  19

In [30]:
df = df.iloc[6130:]
df

A   B
6  6  16
7  7  17
8  8  18
9  9  19

In [24]:
# remove rows starting from index 6 (i.e., rows 6, 7, 8, 9)
df = df.drop(df.index[6:])
df

A   B
0  0  10
1  1  11
2  2  12
3  3  13
4  4  14
5  5  15

In [ ]:
# open and use chardet to detect the encoding
with open('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/normal/WYH_normal1_left1.csv', 'rb') as f:
            data = f.read()
sensor_data = chardet.detect(data)
# Decode the data using the detected encoding
encoding = sensor_data['encoding']
decoded_data = data.decode(encoding)

# Read the CSV file using csv module and convert to a Pandas DataFrame
with open('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/sensor1.csv', 'r', encoding=encoding) as f:
    reader = csv.reader(f)
    data = [row for row in reader]
# Create a dictionary to map the column names to their indices
column_names = {'colunms': 0, 'x': 1, 'y': 2, 'z': 3}
# Convert the data to a Pandas DataFrame and rename the columns
df_sensor_data = pd.DataFrame(data[0:], columns=[key for key in column_names.keys()])
new_sensor_data = df_sensor_data.rename(columns=column_names)
new_sensor_data.columns = ['1', '2', '3', '4']  # rename column
# Print the first 10 rows of the DataFrame
# new_sensor_data.head(15)
new_sensor_data.drop(['1', '3', '4'], axis=1, inplace=True)   # delete multiple columns
# new_sensor_data.head(15)
# delete first 12 row
new_sensor_dat = new_sensor_data.iloc[12:]
# Reset the index
new_data = new_sensor_dat.reset_index(drop=True)
# Print the DataFrame
# new_data
new_data['2'] = new_data['2'].astype(float)
# new_data.dtypes
# new_data.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/normal/name_normal_modified.csv', index=False)
# new_data.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/toein/name_toein_modified.csv', index=False)
# new_data.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/toeout/name_toeout_modified.csv', index=False)
# new_data.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/pronation/name_pronation_modified.csv', index=False)
# new_data.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/supination/name_supination_modified.csv', index=False)


In [10]:
new_dat = pd.read_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/normal/all_WYH_normal2.csv')
new_dat = new_dat.astype(float)
new_dat.dtypes

left1     float64
left2     float64
left3     float64
left4     float64
right1    float64
right2    float64
right3    float64
right4    float64
dtype: object

In [6]:
# save CSV
new_dat.to_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/normal/all_WYH_normal2.csv', index=False)

NameError: name 'new_dat' is not defined

In [22]:
# zero check
zero_check = pd.read_csv('/Users/chenzcha/Desktop/WorkSpace/GaitData_process/WHY_20230211/normal/all_WYH_normal1.csv')
zero_check

left1     left2     left3     left4    right1    right2    right3  \
0      -0.017397 -0.025426  0.020073  0.028102  0.041485 -0.006691  0.111072   
1      -0.017397 -0.054867  0.022749  0.033455  0.041485  0.030779  0.121777   
2      -0.022750 -0.057543  0.041485  0.041485  0.046838  0.041485  0.086984   
3      -0.017397 -0.076278  0.054867  0.044161  0.046838  0.049514  0.084308   
4      -0.022750 -0.046837  0.057543  0.046838  0.041485  0.070926  0.097690   
...          ...       ...       ...       ...       ...       ...       ...   
181875 -0.028103 -0.014720  0.012044  0.014720  0.038808 -0.009367  0.006691   
181876 -0.025426 -0.012044  0.009368  0.022749  0.041485 -0.009367  0.020073   
181877 -0.025426 -0.014720  0.014720  0.022749  0.041485 -0.004014  0.022749   
181878 -0.028103 -0.014720  0.009368  0.022749  0.036132 -0.012044  0.030779   
181879 -0.020073 -0.014720  0.009368  0.017397  0.038808 -0.014720  0.030779   

          right4  
0       0.020073  
1       0.014720  
2       0.006691  
3       0.009368  
4       0.014720  
...          ...  
181875 -0.006691  
181876 -0.009367  
181877 -0.006691  
181878 -0.004014  
181879 -0.001338  

[181880 rows x 8 columns]

In [23]:
zero_check[(zero_check == 0).any(axis=1)].index

Int64Index([ 24878,  24879,  24880,  24881,  24882,  24883,  24884,  24885,
             24886,  24887,
            ...
            166996, 166997, 166998, 166999, 167000, 167001, 167002, 167003,
            167004, 167005],
           dtype='int64', length=3840)

In [36]:
num_zeros_check = (zero_check == 0).sum()
num_zeros_check

left1      180
left2        0
left3        0
left4      108
right1      24
right2    1500
right3    2088
right4       0
dtype: int64

In [14]:
zero_check.iloc[25069:25083]

left1     left2     left3     left4    right1    right2    right3  \
25069 -0.020073  0.028102  0.095013  0.028102  0.046838  0.006691 -0.006691   
25070  0.000000  0.033455 -0.001338  0.028102  0.054867  0.004015 -0.009367   
25071  0.000000  0.025426 -0.038808  0.014720  0.062896  0.004015 -0.009367   
25072  0.000000  0.017397 -0.022750 -0.006691  0.057543  0.014720 -0.004014   
25073  0.000000 -0.012044  0.012044  0.012044  0.052190 -0.033455  0.006691   
25074  0.000000 -0.038808 -0.012044  0.033455  0.044161 -0.070926  0.006691   
25075  0.000000 -0.038808  0.046838  0.028102  0.044161 -0.054867  0.020073   
25076  0.000000 -0.044161  0.081632  0.038808  0.041485 -0.025426  0.022749   
25077  0.000000 -0.092337  0.025426  0.049514  0.033455 -0.022750  0.022749   
25078  0.000000 -0.068249 -0.028103  0.041485  0.044161 -0.017397  0.022749   
25079  0.000000 -0.036132 -0.049514  0.030779  0.054867  0.006691  0.012044   
25080  0.000000 -0.036132 -0.073602  0.009368  0.049514  0.033455  0.014720   
25081  0.000000 -0.025426  0.033455 -0.004014  0.049514  0.038808  0.017397   
25082 -0.022750 -0.017397  0.100366  0.004015  0.044161  0.033455 -0.004014   

         right4  
25069 -0.004014  
25070  0.009368  
25071  0.014720  
25072  0.009368  
25073  0.004015  
25074  0.006691  
25075  0.004015  
25076  0.014720  
25077  0.022749  
25078 -0.001338  
25079 -0.022750  
25080  0.001338  
25081  0.001338  
25082 -0.004014

In [32]:
# matlab zero check
matlab = pd.read_csv('/Users/chenzcha/Desktop/WorkSpace/dat_matrix.csv')
matlab.columns=[1,2,3,4,5,6,7,8]
matlab

1         2         3         4         5         6         7  \
0      -0.017397 -0.054867  0.022749  0.033455  0.041485  0.030779  0.121780   
1      -0.022750 -0.057543  0.041485  0.041485  0.046838  0.041485  0.086984   
2      -0.017397 -0.076278  0.054867  0.044161  0.046838  0.049514  0.084308   
3      -0.022750 -0.046837  0.057543  0.046838  0.041485  0.070926  0.097690   
4      -0.022750 -0.004014  0.046838  0.033455  0.044161  0.089661  0.100370   
...          ...       ...       ...       ...       ...       ...       ...   
181874 -0.028103 -0.014720  0.012044  0.014720  0.038808 -0.009368  0.006691   
181875 -0.025426 -0.012044  0.009368  0.022749  0.041485 -0.009368  0.020073   
181876 -0.025426 -0.014720  0.014720  0.022749  0.041485 -0.004014  0.022749   
181877 -0.028103 -0.014720  0.009368  0.022749  0.036132 -0.012044  0.030779   
181878 -0.020073 -0.014720  0.009368  0.017397  0.038808 -0.014720  0.030779   

               8  
0       0.014720  
1       0.006691  
2       0.009368  
3       0.014720  
4       0.017397  
...          ...  
181874 -0.006692  
181875 -0.009368  
181876 -0.006692  
181877 -0.004014  
181878 -0.001339  

[181879 rows x 8 columns]

In [33]:
matlab[(matlab == 0).any(axis=1)].index

Int64Index([ 24877,  24878,  24879,  24880,  24881,  24882,  24883,  24884,
             24885,  24886,
            ...
            166995, 166996, 166997, 166998, 166999, 167000, 167001, 167002,
            167003, 167004],
           dtype='int64', length=3840)

In [35]:
num_zeros = (matlab == 0).sum()
num_zeros

1     180
2       0
3       0
4     108
5      24
6    1500
7    2088
8       0
dtype: int64